(function ensightenInit(){var ensightenOptions = {client: "kg", clientId: 1318, publishPath: "prod", isPublic:1, serverComponentLocation: "nexus.ensighten.com/kg/prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/kg/prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "true", enablePagePerfBeacon : "true", registryNs : "ensBootstraps", generatedOn : "Thu Mar 09 01:55:49 GMT 2017", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function l(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function m(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,c=0;c<a;c++){var d=b.dataDefinitions[b.dataDefinitionIds[c]];if(!d||
null==d.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var d={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};d.version="1.26.0";d.nexus=f.nexus||"nexus.ensighten.com";d.rand=-1;d.currSec=(new Date).getSeconds();d.options={interval:f.interval||100,erLoc:f.errorLocation||d.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||d.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||d.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||d.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};d.ruleList=[];d.allDeploymentIds=[];d.runDeploymentIds=[];d.runRuleIds=[];d.exceptionList=[];d.ensightenVariables={};d.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;
a.execute()}};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;d.DependencyNotAvailableException=l;m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;d.BeaconException=m;d.checkForInvalidDependencies=function(a,e,c,h){for(a=0;a<c.length;a++)if("DEPENDENCYNEVERAVAILABLE"===c[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new d.DependencyNotAvailableException(h[a])),e&&-1!==e&&d.allDeploymentIds.push(e),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(d.currSec||0)%20,c=d.options.beaconSamplingSeedValue;-1===c?a=!0:0!==b&&0===c%b&&(a=!0)}catch(h){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+d.options.scLoc,!1,a||!0,d.options.scUseCacheBuster)};b.setVariable=function(a,b){d.ensightenVariables[a]=
b};b.getVariable=function(a){return a in d.ensightenVariables?d.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<d.ruleList.length;a++)d.test(d.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();d.exceptionList.push(a);a=window.location.protocol+"//"+d.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(d.options.clientId||-1)+"&client="+encodeURIComponent(d.options.client||"")+"&publishPath="+encodeURIComponent(d.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(e){window[ensightenOptions.ns].reportException(e)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(d.runDeploymentIds.push(this.deploymentId),d.runRuleIds.push(this.id)),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;d.ruleList.push(a);
-1!==a.deploymentId&&d.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<d.ruleList.length;b++)if(d.ruleList[b].id===a)return d.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return d.allDeploymentIds};b.getRunRuleIds=function(){return d.runRuleIds};b.getRunDeploymentIds=function(){return d.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:
!1};d.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+d.toTwoChar(b.getMonth())+"-"+d.toTwoChar(b.getDate())+" "+d.toTwoChar(b.getHours())+":"+d.toTwoChar(b.getMinutes())+":"+d.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);
this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=b.imageRequest(window.location.protocol+"//"+d.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+d.options.clientId+"&client="+d.options.client+"&publishPath="+d.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,c,h){var n=
document.getElementsByTagName("script"),g;h=void 0!==h?h:!0;if(void 0!==e?e:1)for(g=0;g<n.length;g++)if(n[g].src===a&&n[g].readyState&&/loaded|complete/.test(n[g].readyState))return;if(c){c=1==c&&"object"==typeof b.scDataObj?b.scDataObj:c;d.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;"object"===typeof c&&c.PageID&&(e=c.PageID,delete c.PageID);if("object"===typeof c)for(g in c){g=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,g.length?e.length-g.length:
e.length);e+=~e.indexOf("?")?"&":"?";for(k in c)e+=k+"="+c[k]+"&";e=e.slice(0,-1)+g;break}a+="?";h&&(a+="r="+d.rand+"&");a+="ClientID="+encodeURIComponent(d.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var c=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in c){if(!c[0]){setTimeout(arguments.callee,25);return}c=c[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.insertBefore(a,
c.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,c){var e=document.getElementsByTagName("script"),d;c=e[0];for(d=0;d<e.length;d++)if(e[d].src===a&&e[d].readyState&&/loaded|complete/.test(e[d].readyState))try{b()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=a;e.onerror=function(){this.addEventListener&&(this.readyState="loaded")};e.onload=e.onreadystatechange=function(){if(!this.readyState||
"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(g){window[ensightenOptions.ns].reportException(g)}}};c.parentNode.insertBefore(e,c)};b.unobtrusiveAddEvent=function(a,b,c){try{var e=a[b]?a[b]:function(){};a[b]=function(){c.apply(this,arguments);return e.apply(this,arguments)}}catch(n){window[ensightenOptions.ns].reportException(n)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=
e?e:"anonymous",a()}catch(c){window[ensightenOptions.ns].reportException(c)}}};b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,c=0;c<a.length;++c)if(e=b.getRule(parseInt(a[c],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,c,h,f){var g=[];if(!d.checkForInvalidDependencies(e,h,c,f)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,e,c,h,f){var g=[];if(!d.checkForInvalidDependencies(e,h,c,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,c,h,f){var g=[];if(!d.checkForInvalidDependencies(e,
h,c,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,c,h,f){var g=[];if(!d.checkForInvalidDependencies(e,h,c,f)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,c,h,f){var g=[];if(!d.checkForInvalidDependencies(e,h,c,f)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,c,f,n){var g=[];if(!d.checkForInvalidDependencies(e,f,c,n)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:f||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,c=0;c<e;c++){var d=a[c];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(d)&&b.dataDefinitionIds.push(d);else{for(var f=!1,g=b.dataDefinitionIds.length,l=0;l<g;l++)if(b.dataDefinitionIds[l]===d){f=!0;break}f||b.dataDefinitionIds.push(d)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=
a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var c=b.dataDefinitions[e];c||(c=new b.DataDefinition(e,a),b.dataDefinitions[e]=c);c.startRegistrationTime||(c.startRegistration(),c.registrationFn(),c.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=
!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,c=a.length;b<c;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=
a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=
function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var r=function(){var a=[],b=!1,c=!1;return{add:function(e){b&&!c?e():"function"==typeof e&&(a[a.length]=e)},exec:function(){c=!0;do{var e=a;a=[];b=!0;for(var d=0;d<e.length;d++)try{e[d].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);c=!1},haveRun:function(){return b}}};b.new_fArray=
function(){return r()};d.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?
d.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(d.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(e){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",
function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===d.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,c,h,l,g=0;g<d.ruleList.length;++g)c=d.ruleList[g],h=c.executionData.hasRun?"1":"0",l=c.deploymentId.toString()+"|"+c.id.toString()+"|"+h,a.push(l);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+d.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+
"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+e+"&idx=0&r="+d.rand;b.imageRequest(m)}catch(q){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new d.BeaconException(q),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,d.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){var f=f.timing||{},l,m=f.navigationStart||0,p,d={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};l="&ns="+encodeURIComponent(f.navigationStart);for(var b in d)void 0!==f[b]?(p=f[b]-m,l+="&"+d[b]+"="+(0<p?encodeURIComponent(p):0)):l+="&"+d[b]+"=-1";window[ensightenOptions.ns].timing=l;b=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";l=f.indexOf(".com/");m=f.indexOf("/code/");f=f.substring(l+4,m)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+f)}}});
		Bootstrapper.dataDefinitionIds = [];Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();